### ISSUE TITLE
Signup not working

### ISSUE THREAD

**Issue by Foxandxss** [auth0/angular2-authentication-sample#4] opened 2015-05-03 12:38 UTC
Hey Martin, how are you mate?

I love JWT and I try to spread its love as much as possible and this first glance of JWT with Angular 2 is awesome (still too much boilerplate, but awesome nonetheless).

That said, the signup route doesn't work and I hate when I cannot send a PR to fix it because well, I have no clue. Everything seems to be in order.

There is a typo though (PR incoming) but that doesn't fix it.

I also created a KOA backend for the demo (to practice it) and it ended really cool (I can put it on github if you want).

Gracias.

**Comment by PatrickJS** [comment] 2015-05-03 21:31
the problem is partly due to the router

**Comment by Foxandxss** [comment] 2015-05-03 21:33
I am digging all I can to figure how what's happening. It is not routing anything really. You can't go /login nor /signup.

**Comment by PatrickJS** [comment] 2015-05-03 21:57
@Foxandxss the signup link should work now. The state is managing in memory since the location service that manages the url isn't merged yet

**Closed as completed** 2015-05-03 21:56 UTC
